In [ ]:
from mlxtend.frequent_patterns import apriori, fpgrowth, association_rules
from mlxtend.preprocessing import TransactionEncoder
import kagglehub
import pandas as pd

In [ ]:
# Download latest version
path = kagglehub.dataset_download("akashdeepkuila/bakery")

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.7), please consider upgrading to the latest version (0.3.8).

In [ ]:
!ls {path}

Bakery.csv  bakery_sales_revised.csv

# load data

In [ ]:
data = pd.read_csv(path+"/Bakery.csv")
data

       TransactionNo          Items             DateTime    Daypart  DayType
0                  1          Bread  2016-10-30 09:58:11    Morning  Weekend
1                  2   Scandinavian  2016-10-30 10:05:34    Morning  Weekend
2                  2   Scandinavian  2016-10-30 10:05:34    Morning  Weekend
3                  3  Hot chocolate  2016-10-30 10:07:57    Morning  Weekend
4                  3            Jam  2016-10-30 10:07:57    Morning  Weekend
...              ...            ...                  ...        ...      ...
20502           9682         Coffee  2017-09-04 14:32:58  Afternoon  Weekend
20503           9682            Tea  2017-09-04 14:32:58  Afternoon  Weekend
20504           9683         Coffee  2017-09-04 14:57:06  Afternoon  Weekend
20505           9683         Pastry  2017-09-04 14:57:06  Afternoon  Weekend
20506           9684      Smoothies  2017-09-04 15:04:24  Afternoon  Weekend

[20507 rows x 5 columns]

Warning: total number of rows (20507) exceeds max_rows (20000). Limiting to first (20000) rows.

# preprocess data

In [ ]:
transaction_arr = []
for d in data.iloc():
  if d["TransactionNo"] > len(transaction_arr):
    transaction_arr.append([])
  transaction_arr[-1].append(d["Items"])

## encode transactions

In [ ]:
te = TransactionEncoder()

In [ ]:
te_arr = te.fit(transaction_arr).transform(transaction_arr)

In [ ]:
df = pd.DataFrame(te_arr, columns=te.columns_)
df

,Adjustment,Afternoon with the baker,Alfajores,Argentina Night,Art Tray,Bacon,Baguette,Bakewell,Bare Popcorn,Basket,...,The BART,The Nomad,Tiffin,Toast,Truffles,Tshirt,Valentine's card,Vegan Feast,Vegan mincepie,Victorian Sponge
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9679,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9680,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
9681,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9682,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9683,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

# modelling

In [ ]:
freq_items = apriori(df, min_support=0.03, use_colnames=True)

# analysis

In [ ]:
association_rules(freq_items, metric="confidence", min_threshold=0.2)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(Bread),(Coffee),0.320322,0.470363,0.085502,0.266925,0.567486,1.0,-0.065166,0.722486,-0.528603,0.121248,-0.384110,0.224351
1,(Cake),(Coffee),0.101714,0.470363,0.052458,0.515736,1.096463,1.0,0.004615,1.093694,0.097938,0.100954,0.085667,0.313631
2,(Medialuna),(Coffee),0.060409,0.470363,0.033664,0.557265,1.184754,1.0,0.005250,1.196283,0.165969,0.067719,0.164078,0.314417
3,(Pastry),(Coffee),0.084263,0.470363,0.045333,0.537990,1.143775,1.0,0.005698,1.146375,0.137269,0.089011,0.127685,0.317184
4,(Sandwich),(Coffee),0.070322,0.470363,0.036762,0.522761,1.111397,1.0,0.003685,1.109792,0.107813,0.072951,0.098930,0.300458
5,(Tea),(Coffee),0.139715,0.470363,0.047501,0.339985,0.722814,1.0,-0.018216,0.802462,-0.308323,0.084435,-0.246166,0.220487