In [43]:
import numpy as np
import pandas as pd
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge, Lasso, ElasticNet
from sklearn.svm import SVR

from google.colab import drive

In [2]:
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
data = pd.read_csv("/content/drive/MyDrive/B-CODECRUNCH/spotify.csv")

In [47]:
data #print(data)

,track_id,track_name,track_artist,track_popularity,track_album_id,track_album_name,track_album_release_date,playlist_name,playlist_id,playlist_genre,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms
0,6f807x0ima9a1j3VPbc7VN,I Don't Care (with Justin Bieber) - Loud Luxur...,Ed Sheeran,66,2oCs0DGTsRO98Gh5ZSl2Cx,I Don't Care (with Justin Bieber) [Loud Luxury...,2019-06-14,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,6,-2.634,1,0.0583,0.102000,0.000000,0.0653,0.5180,122.036,194754
1,0r7CVbZTWZgbTCYdfa2P31,Memories - Dillon Francis Remix,Maroon 5,67,63rPSO264uRjW1X5E6cWv6,Memories (Dillon Francis Remix),2019-12-13,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,11,-4.969,1,0.0373,0.072400,0.004210,0.3570,0.6930,99.972,162600
2,1z1Hg7Vb0AhHDiEmnDE79l,All the Time - Don Diablo Remix,Zara Larsson,70,1HoSmj2eLcsrR0vE9gThr4,All the Time (Don Diablo Remix),2019-07-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-3.432,0,0.0742,0.079400,0.000023,0.1100,0.6130,124.008,176616
3,75FpbthrwQmzHlBJLuGdC7,Call You Mine - Keanu Silva Remix,The Chainsmokers,60,1nqYsOef1yKKuGOVchbsk6,Call You Mine - The Remixes,2019-07-19,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,7,-3.778,1,0.1020,0.028700,0.000009,0.2040,0.2770,121.956,169093
4,1e8PAfcKUYoKkxPhrHqw4x,Someone You Loved - Future Humans Remix,Lewis Capaldi,69,7m7vv9wlQ4i0LFuJiE2zsQ,Someone You Loved (Future Humans Remix),2019-03-05,Pop Remix,37i9dQZF1DXcZDD7cfEKhW,pop,...,1,-4.672,1,0.0359,0.080300,0.000000,0.0833,0.7250,123.976,189052
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32828,7bxnKAamR3snQ1VGLuVfC1,City Of Lights - Official Radio Edit,Lush & Simon,42,2azRoBBWEEEYhqV6sb7JrT,City Of Lights (Vocal Mix),2014-04-28,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,2,-1.814,1,0.0936,0.076600,0.000000,0.0668,0.2100,128.170,204375
32829,5Aevni09Em4575077nkWHz,Closer - Sultan & Ned Shepard Remix,Tegan and Sara,20,6kD6KLxj7s8eCE3ABvAyf5,Closer Remixed,2013-03-08,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,0,-4.462,1,0.0420,0.001710,0.004270,0.3750,0.4000,128.041,353120
32830,7ImMqPP3Q1yfUHvsdn7wEo,Sweet Surrender - Radio Edit,Starkillers,14,0ltWNSY9JgxoIZO4VzuCa6,Sweet Surrender (Radio Edit),2014-04-21,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,6,-4.899,0,0.0481,0.108000,0.000001,0.1500,0.4360,127.989,210112
32831,2m69mhnfQ1Oq6lGtXuYhgX,Only For You - Maor Levi Remix,Mat Zo,15,1fGrOkHnHJcStl14zNx8Jy,Only For You (Remixes),2014-01-01,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,2,-3.361,1,0.1090,0.007920,0.127000,0.3430,0.3080,128.008,367432
32832,29zWqhca3zt5NsckZqDf6c,Typhoon - Original Mix,Julian Calor,27,0X3mUOm6MhxR7PzxG95rAo,Typhoon/Storm,2014-03-03,♥ EDM LOVE 2020,6jI1gFr6ANFtT8MmTvA2Ux,edm,...,5,-4.571,0,0.0385,0.000133,0.341000,0.7420,0.0894,127.984,337500

In [7]:
X = data[["liveness","tempo","instrumentalness","acousticness"]]
y = data['valence']

In [9]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X,y,train_size=0.9)

In [10]:
Xtrain

       liveness    tempo  instrumentalness  acousticness
12956    0.1750  113.638          0.007070       0.00608
23478    0.1010  106.966          0.000000       0.22900
4620     0.0922  101.979          0.000000       0.45400
28701    0.3030  128.059          0.737000       0.00232
22850    0.0903   91.117          0.305000       0.09280
...         ...      ...               ...           ...
7592     0.0908   77.511          0.000000       0.15100
2507     0.0900   97.990          0.000005       0.05040
18953    0.2640  110.008          0.000451       0.00758
2172     0.1490  111.995          0.000173       0.00205
20577    0.1150  125.973          0.000091       0.27200

[29549 rows x 4 columns]

In [14]:
reg = SVR()
reg.fit(Xtrain, ytrain)
ypred = reg.predict(Xtest)

In [19]:
pd.DataFrame(ypred)

             0
0     0.491218
1     0.554159
2     0.565637
3     0.454402
4     0.448588
...        ...
3279  0.525642
3280  0.565907
3281  0.477231
3282  0.496543
3283  0.491521

[3284 rows x 1 columns]

In [27]:
mean_absolute_error(ytest, ypred)

0.19143078789831652

In [28]:
mean_squared_error(ytest, ypred)

0.05200280003503687

In [33]:
R = Ridge(0.001)
R.fit(Xtrain, ytrain)
ypred2 = R.predict(Xtest)

In [25]:
pd.DataFrame(ypred)

             0
0     0.523063
1     0.536118
2     0.540945
3     0.537355
4     0.487788
...        ...
3279  0.534121
3280  0.531369
3281  0.503858
3282  0.516148
3283  0.542493

[3284 rows x 1 columns]

In [34]:
mean_absolute_error(ytest, ypred2)

0.19143078789831652

In [35]:
mean_squared_error(ytest, ypred2)

0.05200280003503687

In [37]:
L = Lasso(0.001)
L.fit(Xtrain, ytrain)
ypred3 = L.predict(Xtest)

In [39]:
mean_absolute_error(ytest, ypred3)

0.19163931864660896

In [40]:
mean_squared_error(ytest, ypred3)

0.052048792789096236

In [44]:
EN = ElasticNet(0.001)
EN.fit(Xtrain, ytrain)
ypred4 = EN.predict(Xtest)

In [45]:
mean_absolute_error(ytest, ypred4)

0.1915340483670386

In [46]:
mean_squared_error(ytest, ypred4)

0.05201488250733409